name: Publish NuGet Package

permissions:
  contents: read

on:
  push:
    tags:
      - 'v*' # Triggers on version tags like v1.0.0

jobs:
  build:
    runs-on: windows-latest
    environment: Package Creation

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: List working directory
      run: pwd
    
    - name: Ensure packages directory exists
      run: mkdir -p ./nupkgs
    
    - name: Restore dependencies
      run: dotnet restore

    - name: Build the project
      run: dotnet build --configuration Release

    - name: Build and pack
      run: dotnet pack ./LogViewer/LogViewer.csproj --configuration Release --output ./nupkgs

    - name: List nupkgs contents
      run: dir ./nupkgs/*.nupkg

    - name: List working directory
      run: pwd

    - name: Publish to GitHub Packages
      run: dotnet nuget push ./nupkgs/*.nupkg --source "github" --api-key ${{ secrets.GH_PKG_TOKEN }}
      env:
        nuget-api-key: ${{ secrets.GH_PKG_TOKEN }}
